export const REVISION_SHEET_DATA = [
  {
    name: 'Arrays',
    icon: '📊',
    color: '#10b981',
    problems: [
      {
        title: 'Two Sum',
        leetcodeUrl: 'https://leetcode.com/problems/two-sum/',
        articleUrl: '',
        pattern: 'Hashing / Two Pointers',
        url: 'https://leetcode.com/problems/two-sum/',
        difficulty: 'easy',
      },
      {
        title: 'Best Time to Buy and Sell Stock',
        leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
        articleUrl: '',
        pattern: 'Array / DP',
        url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
        difficulty: 'easy',
      },
      {
        title: 'Maximum Subarray',
        leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray/',
        articleUrl: '',
        pattern: "Kadane's Algorithm",
        url: 'https://leetcode.com/problems/maximum-subarray/',
        difficulty: 'medium',
      },
      {
        title: 'Product of Array Except Self',
        leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self/',
        articleUrl: '',
        pattern: 'Prefix/Suffix Product',
        url: 'https://leetcode.com/problems/product-of-array-except-self/',
        difficulty: 'medium',
      },
      {
        title: 'Merge Intervals',
        leetcodeUrl: 'https://leetcode.com/problems/merge-intervals/',
        articleUrl: '',
        pattern: 'Sorting / Intervals',
        url: 'https://leetcode.com/problems/merge-intervals/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'Strings',
    icon: '📝',
    color: '#f59e0b',
    problems: [
      {
        title: 'Valid Anagram',
        leetcodeUrl: 'https://leetcode.com/problems/valid-anagram/',
        articleUrl: '',
        pattern: 'Hashing',
        url: 'https://leetcode.com/problems/valid-anagram/',
        difficulty: 'easy',
      },
      {
        title: 'Longest Substring Without Repeating Characters',
        leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        articleUrl: '',
        pattern: 'Sliding Window',
        url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        difficulty: 'medium',
      },
      {
        title: 'Group Anagrams',
        leetcodeUrl: 'https://leetcode.com/problems/group-anagrams/',
        articleUrl: '',
        pattern: 'Hashing / Sorting',
        url: 'https://leetcode.com/problems/group-anagrams/',
        difficulty: 'medium',
      },
      {
        title: 'Minimum Window Substring',
        leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring/',
        articleUrl: '',
        pattern: 'Variable Sliding Window',
        url: 'https://leetcode.com/problems/minimum-window-substring/',
        difficulty: 'hard',
      },
      {
        title: 'Longest Palindromic Substring',
        leetcodeUrl: 'https://leetcode.com/problems/longest-palindromic-substring/',
        articleUrl: '',
        pattern: 'DP / Expand Around Center',
        url: 'https://leetcode.com/problems/longest-palindromic-substring/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'Linked List',
    icon: '🔗',
    color: '#8b5cf6',
    problems: [
      {
        title: 'Reverse Linked List',
        leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list/',
        articleUrl: '',
        pattern: 'Iterative / Recursive',
        url: 'https://leetcode.com/problems/reverse-linked-list/',
        difficulty: 'easy',
      },
      {
        title: 'Linked List Cycle',
        leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle/',
        articleUrl: '',
        pattern: 'Cycle Detection (Floyd)',
        url: 'https://leetcode.com/problems/linked-list-cycle/',
        difficulty: 'easy',
      },
      {
        title: 'Remove Nth Node From End of List',
        leetcodeUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
        articleUrl: '',
        pattern: 'Slow-Fast Pointer',
        url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
        difficulty: 'medium',
      },
      {
        title: 'Add Two Numbers',
        leetcodeUrl: 'https://leetcode.com/problems/add-two-numbers/',
        articleUrl: '',
        pattern: 'Math Simulation',
        url: 'https://leetcode.com/problems/add-two-numbers/',
        difficulty: 'medium',
      },
      {
        title: 'Merge K Sorted Lists',
        leetcodeUrl: 'https://leetcode.com/problems/merge-k-sorted-lists/',
        articleUrl: '',
        pattern: 'Heap / Divide & Conquer',
        url: 'https://leetcode.com/problems/merge-k-sorted-lists/',
        difficulty: 'hard',
      },
    ],
  },
  {
    name: 'Stack',
    icon: '🧩',
    color: '#6366f1',
    problems: [
      {
        title: 'Valid Parentheses',
        leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses/',
        articleUrl: '',
        pattern: 'Stack Application',
        url: 'https://leetcode.com/problems/valid-parentheses/',
        difficulty: 'easy',
      },
      {
        title: 'Min Stack',
        leetcodeUrl: 'https://leetcode.com/problems/min-stack/',
        articleUrl: '',
        pattern: 'Design + Monotonic',
        url: 'https://leetcode.com/problems/min-stack/',
        difficulty: 'medium',
      },
      {
        title: 'Daily Temperatures',
        leetcodeUrl: 'https://leetcode.com/problems/daily-temperatures/',
        articleUrl: '',
        pattern: 'Monotonic Stack',
        url: 'https://leetcode.com/problems/daily-temperatures/',
        difficulty: 'medium',
      },
      {
        title: 'Largest Rectangle in Histogram',
        leetcodeUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
        articleUrl: '',
        pattern: 'Monotonic Stack',
        url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
        difficulty: 'hard',
      },
    ],
  },
  {
    name: 'Queue',
    icon: '📬',
    color: '#ec4899',
    problems: [
      {
        title: 'Sliding Window Maximum',
        leetcodeUrl: 'https://leetcode.com/problems/sliding-window-maximum/',
        articleUrl: '',
        pattern: 'Monotonic Deque',
        url: 'https://leetcode.com/problems/sliding-window-maximum/',
        difficulty: 'hard',
      },
    ],
  },
  {
    name: 'Binary Search',
    icon: '🔍',
    color: '#06b6d4',
    problems: [
      {
        title: 'Binary Search',
        leetcodeUrl: 'https://leetcode.com/problems/binary-search/',
        articleUrl: '',
        pattern: 'BS Fundamentals',
        url: 'https://leetcode.com/problems/binary-search/',
        difficulty: 'easy',
      },
      {
        title: 'Search in Rotated Sorted Array',
        leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
        articleUrl: '',
        pattern: 'BS on Rotated Array',
        url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
        difficulty: 'medium',
      },
      {
        title: 'Koko Eating Bananas',
        leetcodeUrl: 'https://leetcode.com/problems/koko-eating-bananas/',
        articleUrl: '',
        pattern: 'BS on Answer',
        url: 'https://leetcode.com/problems/koko-eating-bananas/',
        difficulty: 'medium',
      },
      {
        title: 'Find Minimum in Rotated Sorted Array',
        leetcodeUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
        articleUrl: '',
        pattern: 'BS on Rotated Array',
        url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'Trees',
    icon: '🌳',
    color: '#14b8a6',
    problems: [
      {
        title: 'Binary Tree Level Order Traversal',
        leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
        articleUrl: '',
        pattern: 'BFS',
        url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
        difficulty: 'medium',
      },
      {
        title: 'Maximum Depth of Binary Tree',
        leetcodeUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        articleUrl: '',
        pattern: 'Tree DFS',
        url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        difficulty: 'easy',
      },
      {
        title: 'Diameter of Binary Tree',
        leetcodeUrl: 'https://leetcode.com/problems/diameter-of-binary-tree/',
        articleUrl: '',
        pattern: 'Tree DFS',
        url: 'https://leetcode.com/problems/diameter-of-binary-tree/',
        difficulty: 'easy',
      },
      {
        title: 'Lowest Common Ancestor of Binary Tree',
        leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
        articleUrl: '',
        pattern: 'Tree DFS',
        url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'BST',
    icon: '🌲',
    color: '#84cc16',
    problems: [
      {
        title: 'Validate Binary Search Tree',
        leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree/',
        articleUrl: '',
        pattern: 'Valid BST',
        url: 'https://leetcode.com/problems/validate-binary-search-tree/',
        difficulty: 'medium',
      },
      {
        title: 'Kth Smallest Element in a BST',
        leetcodeUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
        articleUrl: '',
        pattern: 'BST Inorder',
        url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'Heap',
    icon: '🔺',
    color: '#f97316',
    problems: [
      {
        title: 'Kth Largest Element in an Array',
        leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
        articleUrl: '',
        pattern: 'Heap / QuickSelect',
        url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
        difficulty: 'medium',
      },
      {
        title: 'Top K Frequent Elements',
        leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements/',
        articleUrl: '',
        pattern: 'Heap + HashMap',
        url: 'https://leetcode.com/problems/top-k-frequent-elements/',
        difficulty: 'medium',
      },
      {
        title: 'Find Median from Data Stream',
        leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream/',
        articleUrl: '',
        pattern: 'Two Heaps',
        url: 'https://leetcode.com/problems/find-median-from-data-stream/',
        difficulty: 'hard',
      },
    ],
  },
  {
    name: 'Graphs',
    icon: '🕸️',
    color: '#f43f5e',
    problems: [
      {
        title: 'Number of Islands',
        leetcodeUrl: 'https://leetcode.com/problems/number-of-islands/',
        articleUrl: '',
        pattern: 'BFS/DFS on Grid',
        url: 'https://leetcode.com/problems/number-of-islands/',
        difficulty: 'medium',
      },
      {
        title: 'Clone Graph',
        leetcodeUrl: 'https://leetcode.com/problems/clone-graph/',
        articleUrl: '',
        pattern: 'DFS/BFS',
        url: 'https://leetcode.com/problems/clone-graph/',
        difficulty: 'medium',
      },
      {
        title: 'Course Schedule',
        leetcodeUrl: 'https://leetcode.com/problems/course-schedule/',
        articleUrl: '',
        pattern: 'Cycle Detection (Topo)',
        url: 'https://leetcode.com/problems/course-schedule/',
        difficulty: 'medium',
      },
      {
        title: 'Rotting Oranges',
        leetcodeUrl: 'https://leetcode.com/problems/rotting-oranges/',
        articleUrl: '',
        pattern: 'BFS on Grid',
        url: 'https://leetcode.com/problems/rotting-oranges/',
        difficulty: 'medium',
      },
      {
        title: 'Network Delay Time',
        leetcodeUrl: 'https://leetcode.com/problems/network-delay-time/',
        articleUrl: '',
        pattern: 'Dijkstra',
        url: 'https://leetcode.com/problems/network-delay-time/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'Backtracking',
    icon: '🔄',
    color: '#a855f7',
    problems: [
      {
        title: 'Subsets',
        leetcodeUrl: 'https://leetcode.com/problems/subsets/',
        articleUrl: '',
        pattern: 'Recursion / Iterative',
        url: 'https://leetcode.com/problems/subsets/',
        difficulty: 'medium',
      },
      {
        title: 'Combination Sum',
        leetcodeUrl: 'https://leetcode.com/problems/combination-sum/',
        articleUrl: '',
        pattern: 'Combination Sum',
        url: 'https://leetcode.com/problems/combination-sum/',
        difficulty: 'medium',
      },
      {
        title: 'Permutations',
        leetcodeUrl: 'https://leetcode.com/problems/permutations/',
        articleUrl: '',
        pattern: 'All Arrangements',
        url: 'https://leetcode.com/problems/permutations/',
        difficulty: 'medium',
      },
      {
        title: 'N-Queens',
        leetcodeUrl: 'https://leetcode.com/problems/n-queens/',
        articleUrl: '',
        pattern: 'Constraint Satisfaction',
        url: 'https://leetcode.com/problems/n-queens/',
        difficulty: 'hard',
      },
    ],
  },
  {
    name: 'Greedy',
    icon: '💡',
    color: '#eab308',
    problems: [
      {
        title: 'Jump Game',
        leetcodeUrl: 'https://leetcode.com/problems/jump-game/',
        articleUrl: '',
        pattern: 'Greedy Reachability',
        url: 'https://leetcode.com/problems/jump-game/',
        difficulty: 'medium',
      },
      {
        title: 'Gas Station',
        leetcodeUrl: 'https://leetcode.com/problems/gas-station/',
        articleUrl: '',
        pattern: 'Greedy Circular',
        url: 'https://leetcode.com/problems/gas-station/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'Dynamic Programming',
    icon: '🧮',
    color: '#3b82f6',
    problems: [
      {
        title: 'Climbing Stairs',
        leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs/',
        articleUrl: '',
        pattern: 'Fibonacci DP',
        url: 'https://leetcode.com/problems/climbing-stairs/',
        difficulty: 'easy',
      },
      {
        title: 'House Robber',
        leetcodeUrl: 'https://leetcode.com/problems/house-robber/',
        articleUrl: '',
        pattern: 'Max Non-Adjacent Sum',
        url: 'https://leetcode.com/problems/house-robber/',
        difficulty: 'medium',
      },
      {
        title: 'Coin Change',
        leetcodeUrl: 'https://leetcode.com/problems/coin-change/',
        articleUrl: '',
        pattern: 'Unbounded Knapsack',
        url: 'https://leetcode.com/problems/coin-change/',
        difficulty: 'medium',
      },
      {
        title: 'Longest Common Subsequence',
        leetcodeUrl: 'https://leetcode.com/problems/longest-common-subsequence/',
        articleUrl: '',
        pattern: 'String DP',
        url: 'https://leetcode.com/problems/longest-common-subsequence/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'Trie',
    icon: '🌐',
    color: '#06b6d4',
    problems: [
      {
        title: 'Implement Trie (Prefix Tree)',
        leetcodeUrl: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
        articleUrl: '',
        pattern: 'Trie Implementation',
        url: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
        difficulty: 'medium',
      },
    ],
  },
  {
    name: 'Union Find',
    icon: '🔀',
    color: '#64748b',
    problems: [
      {
        title: 'Number of Provinces',
        leetcodeUrl: 'https://leetcode.com/problems/number-of-provinces/',
        articleUrl: '',
        pattern: 'Connected Components / DSU',
        url: 'https://leetcode.com/problems/number-of-provinces/',
        difficulty: 'medium',
      },
    ],
  },
];
