export const STRIVER_SHEET_DATA = [
  {
    name: 'Arrays',
    icon: '📊',
    color: '#10b981',
    problems: [
      { title: "Largest Element in an Array",  leetcodeUrl: "https://leetcode.com/problems/largest-number/", articleUrl: "", pattern: "Array Basics" },
      { title: "Second Largest Element",  leetcodeUrl: "https://leetcode.com/problems/second-largest-digit-in-a-string/", articleUrl: "", pattern: "Array Basics" },
      { title: "Check if Array is Sorted",  leetcodeUrl: "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/", articleUrl: "", pattern: "Array Basics" },
      { title: "Remove Duplicates from Sorted Array",  leetcodeUrl: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", articleUrl: "", pattern: "Two Pointers" },
      { title: "Left Rotate an Array by One",  url: "https://www.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one2614/1", articleUrl: "", pattern: "Array Basics" },
      { title: "Left Rotate an Array by D Places",  leetcodeUrl: "https://leetcode.com/problems/rotate-array/", articleUrl: "", pattern: "Array Basics" },
      { title: "Move Zeroes to End",  leetcodeUrl: "https://leetcode.com/problems/move-zeroes/", articleUrl: "", pattern: "Two Pointers" },
      { title: "Linear Search",  url: "https://www.geeksforgeeks.org/problems/search-an-element-in-an-array-1587115621/1", articleUrl: "", pattern: "Array Basics" },
      { title: "Union of Two Sorted Arrays",  url: "https://www.geeksforgeeks.org/problems/union-of-two-arrays3538/1", articleUrl: "", pattern: "Two Pointers" },
      { title: "Intersection of Two Sorted Arrays",  leetcodeUrl: "https://leetcode.com/problems/intersection-of-two-arrays/", articleUrl: "", pattern: "Two Pointers" },
      { title: "Find Missing Number in Array",  leetcodeUrl: "https://leetcode.com/problems/missing-number/", articleUrl: "", pattern: "Math" },
      { title: "Maximum Consecutive Ones",  leetcodeUrl: "https://leetcode.com/problems/max-consecutive-ones/", articleUrl: "", pattern: "Sliding Window" },
      { title: "Find the Number that Appears Once (Single Number)",  leetcodeUrl: "https://leetcode.com/problems/single-number/", articleUrl: "", pattern: "Bit Manipulation" },
      { title: "Longest Subarray with Sum K (Positives)",  url: "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1", articleUrl: "", pattern: "Sliding Window / Prefix Sum" },
      { title: "Longest Subarray with Sum K (Positives + Negatives)",  url: "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1", articleUrl: "", pattern: "Prefix Sum / Hashing" },
      { title: "2Sum Problem",  leetcodeUrl: "https://leetcode.com/problems/two-sum/", articleUrl: "", pattern: "Hashing / Two Pointers" },
      { title: "Sort an Array of 0s 1s and 2s",  leetcodeUrl: "https://leetcode.com/problems/sort-colors/", articleUrl: "", pattern: "Three Pointers" },
      { title: "Majority Element (>n/2 times)",  leetcodeUrl: "https://leetcode.com/problems/majority-element/", articleUrl: "", pattern: "Moore's Voting" },
      { title: "Majority Element II (>n/3 times)",  leetcodeUrl: "https://leetcode.com/problems/majority-element-ii/", articleUrl: "", pattern: "Extended Moore's Voting" },
      { title: "Maximum Subarray Sum (Kadane's Algo)",  leetcodeUrl: "https://leetcode.com/problems/maximum-subarray/", articleUrl: "", pattern: "Dynamic Programming / Kadane" },
      { title: "Best Time to Buy and Sell Stock",  leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", articleUrl: "", pattern: "Array / DP" },
      { title: "Rearrange Array Elements by Sign",  leetcodeUrl: "https://leetcode.com/problems/rearrange-array-elements-by-sign/", articleUrl: "", pattern: "Two Pointers" },
      { title: "Next Permutation",  leetcodeUrl: "https://leetcode.com/problems/next-permutation/", articleUrl: "", pattern: "Array Mathematics" },
      { title: "Leaders in an Array",  url: "https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1", articleUrl: "", pattern: "Array Traversal" },
      { title: "Longest Consecutive Sequence",  leetcodeUrl: "https://leetcode.com/problems/longest-consecutive-sequence/", articleUrl: "", pattern: "Hashing" },
      { title: "Set Matrix Zeroes",  leetcodeUrl: "https://leetcode.com/problems/set-matrix-zeroes/", articleUrl: "", pattern: "Matrix" },
      { title: "Rotate Matrix by 90 Degrees",  leetcodeUrl: "https://leetcode.com/problems/rotate-image/", articleUrl: "", pattern: "Matrix" },
      { title: "Spiral Matrix",  leetcodeUrl: "https://leetcode.com/problems/spiral-matrix/", articleUrl: "", pattern: "Matrix Simulation" },
      { title: "Count Subarrays with Given Sum",  leetcodeUrl: "https://leetcode.com/problems/subarray-sum-equals-k/", articleUrl: "", pattern: "Prefix Sum / Hashing" },
      { title: "Pascal's Triangle",  leetcodeUrl: "https://leetcode.com/problems/pascals-triangle/", articleUrl: "", pattern: "DP / Combinatorics" },
      { title: "Majority Element (N/3)",  url: "https://www.geeksforgeeks.org/problems/majority-element-ii/1", articleUrl: "", pattern: "Moore's Voting" },
      { title: "3Sum Problem",  leetcodeUrl: "https://leetcode.com/problems/3sum/", articleUrl: "", pattern: "Two Pointers / Sorting" },
      { title: "4Sum Problem",  leetcodeUrl: "https://leetcode.com/problems/4sum/", articleUrl: "", pattern: "Two Pointers / Sorting" },
      { title: "Subarray with 0 sum",  url: "https://www.geeksforgeeks.org/problems/subarray-with-0-sum-1587115621/1", articleUrl: "", pattern: "Prefix Sum / Hashing" },
      { title: "Merge Overlapping Intervals",  leetcodeUrl: "https://leetcode.com/problems/merge-intervals/", articleUrl: "", pattern: "Sorting / Intervals" },
      { title: "Count Inversions",  url: "https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1", articleUrl: "", pattern: "Divide and Conquer (Merge Sort)" },
      { title: "Reverse Pairs",  leetcodeUrl: "https://leetcode.com/problems/reverse-pairs/", articleUrl: "", pattern: "Divide and Conquer (Merge Sort)" },
      { title: "Maximum Product Subarray",  leetcodeUrl: "https://leetcode.com/problems/maximum-product-subarray/", articleUrl: "", pattern: "Kadane's Variation" },
    ]
  },
  {
    name: 'Binary Search',
    icon: '🔍',
    color: '#06b6d4',
    problems: [
      { title: "Binary Search on 1D Array",  leetcodeUrl: "https://leetcode.com/problems/binary-search/", articleUrl: "", pattern: "BS Fundamentals" },
      { title: "Floor and Ceil in Sorted Array",  url: "https://www.geeksforgeeks.org/problems/floor-in-a-sorted-array-1587115620/1", articleUrl: "", pattern: "BS on Array" },
      { title: "First and Last Position of Element",  leetcodeUrl: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", articleUrl: "", pattern: "BS on Array" },
      { title: "Search in Rotated Sorted Array I",  leetcodeUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array/", articleUrl: "", pattern: "BS on Rotated Array" },
      { title: "Search in Rotated Sorted Array II",  leetcodeUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/", articleUrl: "", pattern: "BS on Rotated Array" },
      { title: "Find Minimum in Rotated Sorted Array",  leetcodeUrl: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", articleUrl: "", pattern: "BS on Rotated Array" },
      { title: "Find Peak Element",  leetcodeUrl: "https://leetcode.com/problems/find-peak-element/", articleUrl: "", pattern: "BS on Unsorted Array" },
      { title: "Square Root of a Number",  leetcodeUrl: "https://leetcode.com/problems/sqrtx/", articleUrl: "", pattern: "BS on Answer" },
      { title: "Koko Eating Bananas",  leetcodeUrl: "https://leetcode.com/problems/koko-eating-bananas/", articleUrl: "", pattern: "BS on Answer" },
      { title: "Minimum Number of Days to Make m Bouquets",  leetcodeUrl: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/", articleUrl: "", pattern: "BS on Answer" },
      { title: "Find the Smallest Divisor Given a Threshold",  leetcodeUrl: "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/", articleUrl: "", pattern: "BS on Answer" },
      { title: "Capacity to Ship Packages within D Days",  leetcodeUrl: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", articleUrl: "", pattern: "BS on Answer" },
      { title: "Kth Missing Positive Number",  leetcodeUrl: "https://leetcode.com/problems/kth-missing-positive-number/", articleUrl: "", pattern: "BS on Answer" },
      { title: "Aggressive Cows",  url: "https://www.geeksforgeeks.org/problems/aggressive-cows/1", articleUrl: "", pattern: "BS on Answer" },
      { title: "Allocate Books",  url: "https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1", articleUrl: "", pattern: "BS on Answer" },
      { title: "Split Array Largest Sum",  leetcodeUrl: "https://leetcode.com/problems/split-array-largest-sum/", articleUrl: "", pattern: "BS on Answer" },
      { title: "Median of Two Sorted Arrays",  leetcodeUrl: "https://leetcode.com/problems/median-of-two-sorted-arrays/", articleUrl: "", pattern: "BS on Two Arrays" },
      { title: "K-th Element of Two Sorted Arrays",  url: "https://www.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1", articleUrl: "", pattern: "BS on Two Arrays" },
      { title: "Row with Maximum 1s",  url: "https://www.geeksforgeeks.org/problems/row-with-max-1s0023/1", articleUrl: "", pattern: "BS in 2D" },
      { title: "Search in a 2D Matrix I",  leetcodeUrl: "https://leetcode.com/problems/search-a-2d-matrix/", articleUrl: "", pattern: "BS in 2D" },
      { title: "Search in a 2D Matrix II",  leetcodeUrl: "https://leetcode.com/problems/search-a-2d-matrix-ii/", articleUrl: "", pattern: "BS in 2D" },
      { title: "Find Peak Element II",  leetcodeUrl: "https://leetcode.com/problems/find-a-peak-element-ii/", articleUrl: "", pattern: "BS in 2D" },
      { title: "Median in a Row-wise Sorted Matrix",  url: "https://www.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1", articleUrl: "", pattern: "BS in 2D" },
    ]
  },
  {
    name: 'Strings',
    icon: '📝',
    color: '#f59e0b',
    problems: [
      { title: "Remove Outermost Parentheses",  leetcodeUrl: "https://leetcode.com/problems/remove-outermost-parentheses/", articleUrl: "", pattern: "Stack/String Basics" },
      { title: "Reverse Words in a String",  leetcodeUrl: "https://leetcode.com/problems/reverse-words-in-a-string/", articleUrl: "", pattern: "String Manipulation" },
      { title: "Largest Odd Number in String",  leetcodeUrl: "https://leetcode.com/problems/largest-odd-number-in-string/", articleUrl: "", pattern: "String Traversal" },
      { title: "Longest Common Prefix",  leetcodeUrl: "https://leetcode.com/problems/longest-common-prefix/", articleUrl: "", pattern: "Trie/String Sorting" },
      { title: "Isomorphic Strings",  leetcodeUrl: "https://leetcode.com/problems/isomorphic-strings/", articleUrl: "", pattern: "Hashing" },
      { title: "Rotate String",  leetcodeUrl: "https://leetcode.com/problems/rotate-string/", articleUrl: "", pattern: "String Matching" },
      { title: "Valid Anagram",  leetcodeUrl: "https://leetcode.com/problems/valid-anagram/", articleUrl: "", pattern: "Hashing" },
      { title: "Sort Characters by Frequency",  leetcodeUrl: "https://leetcode.com/problems/sort-characters-by-frequency/", articleUrl: "", pattern: "Sorting/Hashing" },
      { title: "Maximum Nesting Depth of Parentheses",  leetcodeUrl: "https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/", articleUrl: "", pattern: "Stack" },
      { title: "Roman to Integer",  leetcodeUrl: "https://leetcode.com/problems/roman-to-integer/", articleUrl: "", pattern: "Simulation/Hashing" },
      { title: "String to Integer (atoi)",  leetcodeUrl: "https://leetcode.com/problems/string-to-integer-atoi/", articleUrl: "", pattern: "Simulation" },
      { title: "Count With K Different Characters",  url: "https://www.geeksforgeeks.org/problems/longest-k-unique-characters-substring0853/1", articleUrl: "", pattern: "Sliding Window" },
      { title: "Longest Substring Without Repeating Characters",  leetcodeUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", articleUrl: "", pattern: "Sliding Window" },
      { title: "Longest Palindromic Substring",  leetcodeUrl: "https://leetcode.com/problems/longest-palindromic-substring/", articleUrl: "", pattern: "DP / Expand Around Center" },
      { title: "Sum of Beauty of All Substrings",  leetcodeUrl: "https://leetcode.com/problems/sum-of-beauty-of-all-substrings/", articleUrl: "", pattern: "Sliding Window/DP" },
      { title: "Minimum Add to Make Parentheses Valid",  leetcodeUrl: "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/", articleUrl: "", pattern: "Stack" },
      { title: "Count and Say",  leetcodeUrl: "https://leetcode.com/problems/count-and-say/", articleUrl: "", pattern: "Simulation" },
      { title: "Compare Version Numbers",  leetcodeUrl: "https://leetcode.com/problems/compare-version-numbers/", articleUrl: "", pattern: "Tokenisation" },
      { title: "Shortest Palindrome (KMP)",  leetcodeUrl: "https://leetcode.com/problems/shortest-palindrome/", articleUrl: "", pattern: "KMP" },
      { title: "Longest Happy Prefix",  leetcodeUrl: "https://leetcode.com/problems/longest-happy-prefix/", articleUrl: "", pattern: "KMP" },
      { title: "Repeated String Match (Rabin-Karp)",  leetcodeUrl: "https://leetcode.com/problems/repeated-string-match/", articleUrl: "", pattern: "Rabin-Karp" },
      { title: "Find the Index of First Occurrence in a String",  leetcodeUrl: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/", articleUrl: "", pattern: "Pattern Matching" },
      { title: "Valid Palindrome II",  leetcodeUrl: "https://leetcode.com/problems/valid-palindrome-ii/", articleUrl: "", pattern: "Two Pointers" },
      { title: "Minimum Characters for Palindrome",  url: "https://www.geeksforgeeks.org/problems/minimum-characters-to-be-added-at-front-to-make-string-palindrome4547/1", articleUrl: "", pattern: "LPS Array" },
      { title: "Z-Function",  url: "https://www.geeksforgeeks.org/problems/z-function/1", articleUrl: "", pattern: "Z-Algorithm" },
    ]
  },
  {
    name: 'LinkedList',
    icon: '🔗',
    color: '#8b5cf6',
    problems: [
      { title: "Introduction to Linked List",  leetcodeUrl: "", articleUrl: "", pattern: "Basic Operations" },
      { title: "Insertion and Deletion in LL",  leetcodeUrl: "", articleUrl: "", pattern: "Basic Operations" },
      { title: "Find Length of Loop",  url: "https://www.geeksforgeeks.org/problems/find-length-of-loop/1", articleUrl: "", pattern: "Cycle Detection" },
      { title: "Middle of Linked List",  leetcodeUrl: "https://leetcode.com/problems/middle-of-the-linked-list/", articleUrl: "", pattern: "Slow-Fast Pointer" },
      { title: "Reverse a Linked List",  leetcodeUrl: "https://leetcode.com/problems/reverse-linked-list/", articleUrl: "", pattern: "Iterative/Recursive" },
      { title: "Detect a Loop in LL",  leetcodeUrl: "https://leetcode.com/problems/linked-list-cycle/", articleUrl: "", pattern: "Cycle Detection" },
      { title: "Start of Loop in LL",  leetcodeUrl: "https://leetcode.com/problems/linked-list-cycle-ii/", articleUrl: "", pattern: "Cycle Detection" },
      { title: "Palindrome Linked List",  leetcodeUrl: "https://leetcode.com/problems/palindrome-linked-list/", articleUrl: "", pattern: "Reversal + Two Pointers" },
      { title: "Odd Even Linked List",  leetcodeUrl: "https://leetcode.com/problems/odd-even-linked-list/", articleUrl: "", pattern: "Pointer Manipulation" },
      { title: "Delete Middle of LL",  leetcodeUrl: "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/", articleUrl: "", pattern: "Slow-Fast Pointer" },
      { title: "Sort LL",  leetcodeUrl: "https://leetcode.com/problems/sort-list/", articleUrl: "", pattern: "Merge Sort on LL" },
      { title: "Remove N-th Node from Back",  leetcodeUrl: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", articleUrl: "", pattern: "Slow-Fast Pointer" },
      { title: "Delete Node without Head",  leetcodeUrl: "https://leetcode.com/problems/delete-node-in-a-linked-list/", articleUrl: "", pattern: "Pointer Trick" },
      { title: "Intersection of Two Linked Lists",  leetcodeUrl: "https://leetcode.com/problems/intersection-of-two-linked-lists/", articleUrl: "", pattern: "Hashing/Two Pointers" },
      { title: "Add Two Numbers in LL",  leetcodeUrl: "https://leetcode.com/problems/add-two-numbers/", articleUrl: "", pattern: "Math Simulation" },
      { title: "Add 1 to a Number Represented as LL",  url: "https://www.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1", articleUrl: "", pattern: "Recursion" },
      { title: "Reverse Nodes in k-Group",  leetcodeUrl: "https://leetcode.com/problems/reverse-nodes-in-k-group/", articleUrl: "", pattern: "Recursion/Iterative" },
      { title: "Rotate a LL",  leetcodeUrl: "https://leetcode.com/problems/rotate-list/", articleUrl: "", pattern: "Circular Trick" },
      { title: "Flattening a LL",  url: "https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1", articleUrl: "", pattern: "Recursion/Heap" },
      { title: "Clone a LL with Random Pointers",  leetcodeUrl: "https://leetcode.com/problems/copy-list-with-random-pointer/", articleUrl: "", pattern: "Hashing/Link Manipulation" },
      { title: "LRU Cache",  leetcodeUrl: "https://leetcode.com/problems/lru-cache/", articleUrl: "", pattern: "Design + Doubly Linked List" },
      { title: "LFU Cache",  leetcodeUrl: "https://leetcode.com/problems/lfu-cache/", articleUrl: "", pattern: "Design + Frequency" },
    ]
  },
  {
    name: 'Prefix Sum / Hashing',
    icon: '🌳',
    color: '#f43f5e',
    problems: [
      { title: "Count All Subarrays with Given Sum",  url: "https://www.geeksforgeeks.org/problems/subarray-range-with-given-sum2804/1", articleUrl: "", pattern: "Prefix Sum" },
      { title: "Number of Submatrices that Sum to Target",  leetcodeUrl: "https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/", articleUrl: "", pattern: "2D Prefix + Hashmap" },
      { title: "Longest Subarray with Sum Divisible by K",  url: "https://www.geeksforgeeks.org/problems/longest-subarray-with-sum-divisible-by-k1259/1", articleUrl: "", pattern: "Modulo Hashmap" },
      { title: "Subarray Sum Divisible by K",  leetcodeUrl: "https://leetcode.com/problems/subarray-sums-divisible-by-k/", articleUrl: "", pattern: "Modulo Hashmap" },
      { title: "Longest Subarray with Sum K (Pos + Neg)",  leetcodeUrl: "", articleUrl: "", pattern: "Prefix Sum Map" }
    ]
  },
  {
    name: 'Two Pointers / Sliding Window',
    icon: '🌲',
    color: '#3b82f6',
    problems: [
      { title: "Fruit Into Baskets",  leetcodeUrl: "https://leetcode.com/problems/fruit-into-baskets/", articleUrl: "", pattern: "Variable Sliding Window" },
      { title: "Longest Repeating Character Replacement",  leetcodeUrl: "https://leetcode.com/problems/longest-repeating-character-replacement/", articleUrl: "", pattern: "Variable Sliding Window" },
      { title: "Binary Subarrays With Sum",  leetcodeUrl: "https://leetcode.com/problems/binary-subarrays-with-sum/", articleUrl: "", pattern: "AtMost Trick" },
      { title: "Count Number of Nice Subarrays",  leetcodeUrl: "https://leetcode.com/problems/count-number-of-nice-subarrays/", articleUrl: "", pattern: "AtMost Trick" },
      { title: "Number of Substrings Containing All Three Characters",  leetcodeUrl: "https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/", articleUrl: "", pattern: "Variable Sliding Window" },
      { title: "Max Consecutive Ones III",  leetcodeUrl: "https://leetcode.com/problems/max-consecutive-ones-iii/", articleUrl: "", pattern: "Variable Sliding Window" },
      { title: "Longest Substring with At Most K Distinct Characters",  url: "https://www.geeksforgeeks.org/problems/longest-k-unique-characters-substring0853/1", articleUrl: "", pattern: "Variable Sliding Window" },
      { title: "Minimum Window Substring",  leetcodeUrl: "https://leetcode.com/problems/minimum-window-substring/", articleUrl: "", pattern: "Variable Sliding Window" },
      { title: "Minimum Window Subsequence",  leetcodeUrl: "", articleUrl: "", pattern: "DP / Two Pointers" },
      { title: "Subarrays with exactly K different integers",  leetcodeUrl: "https://leetcode.com/problems/subarrays-with-k-different-integers/", articleUrl: "", pattern: "AtMost(K) - AtMost(K-1)" },
      { title: "4Sum",  leetcodeUrl: "https://leetcode.com/problems/4sum/", articleUrl: "", pattern: "Sort + Two Pointers" },
    ]
  },
  {
    name: 'Math',
    icon: '🎲',
    color: '#14b8a6',
    problems: [
      { title: "Number of Subarrays with GCD equals K",  url: "https://www.geeksforgeeks.org/problems/number-of-subarrays-with-gcd-equal-to-k/1", articleUrl: "", pattern: "Prefix GCD" },
      { title: "All Divisors of a Number",  url: "https://www.geeksforgeeks.org/problems/all-divisors-of-a-number/1", articleUrl: "", pattern: "Math Fundamentals" },
      { title: "Check Prime",  leetcodeUrl: "", articleUrl: "", pattern: "Math" },
      { title: "Sieve of Eratosthenes",  url: "https://www.geeksforgeeks.org/problems/sieve-of-eratosthenes5242/1", articleUrl: "", pattern: "Prime Generation" },
      { title: "Prime Factorisation",  leetcodeUrl: "", articleUrl: "", pattern: "Math" },
      { title: "Count Primes",  leetcodeUrl: "https://leetcode.com/problems/count-primes/", articleUrl: "", pattern: "Sieve" },
      { title: "GCD / LCM",  url: "https://www.geeksforgeeks.org/problems/lcm-and-gcd4516/1", articleUrl: "", pattern: "Euclidean Algorithm" },
      { title: "Armstrong Numbers",  url: "https://www.geeksforgeeks.org/problems/armstrong-numbers2727/1", articleUrl: "", pattern: "Math" },
      { title: "Palindrome Number",  leetcodeUrl: "https://leetcode.com/problems/palindrome-number/", articleUrl: "", pattern: "Math" },
      { title: "Reverse Integer",  leetcodeUrl: "https://leetcode.com/problems/reverse-integer/", articleUrl: "", pattern: "Math Overflow Handle" },
      { title: "Count Digits",  url: "https://www.geeksforgeeks.org/problems/count-digits5716/1", articleUrl: "", pattern: "Math" },
      { title: "Pow(x",  leetcodeUrl: "https://leetcode.com/problems/powx-n/", articleUrl: "", pattern: "Basic Math" },
    ]
  },
  {
    name: 'Stack and Queue',
    icon: '🧩',
    color: '#6366f1',
    problems: [
      { title: "Implement Stack using Arrays",  leetcodeUrl: "", articleUrl: "", pattern: "Basic Stack Implementation" },
      { title: "Implement Queue using Arrays",  leetcodeUrl: "", articleUrl: "", pattern: "Basic Queue Implementation" },
      { title: "Implement Stack using Queue",  leetcodeUrl: "https://leetcode.com/problems/implement-stack-using-queues/", articleUrl: "", pattern: "Design" },
      { title: "Implement Queue using Stack",  leetcodeUrl: "https://leetcode.com/problems/implement-queue-using-stacks/", articleUrl: "", pattern: "Design" },
      { title: "Valid Parentheses",  leetcodeUrl: "https://leetcode.com/problems/valid-parentheses/", articleUrl: "", pattern: "Stack Application" },
      { title: "Min Stack",  leetcodeUrl: "https://leetcode.com/problems/min-stack/", articleUrl: "", pattern: "Design + Monotonic" },
      { title: "Next Greater Element I",  leetcodeUrl: "https://leetcode.com/problems/next-greater-element-i/", articleUrl: "", pattern: "Monotonic Stack" },
      { title: "Next Greater Element II",  leetcodeUrl: "https://leetcode.com/problems/next-greater-element-ii/", articleUrl: "", pattern: "Monotonic Stack (Circular)" },
      { title: "Previous Smaller Element",  url: "https://www.geeksforgeeks.org/problems/smallest-number-on-left3403/1", articleUrl: "", pattern: "Monotonic Stack" },
      { title: "Trapping Rain Water",  leetcodeUrl: "https://leetcode.com/problems/trapping-rain-water/", articleUrl: "", pattern: "Two Pointers / Monotonic Stack" },
      { title: "Sum of Subarray Minimums",  leetcodeUrl: "https://leetcode.com/problems/sum-of-subarray-minimums/", articleUrl: "", pattern: "Monotonic Stack" },
      { title: "Asteroid Collision",  leetcodeUrl: "https://leetcode.com/problems/asteroid-collision/", articleUrl: "", pattern: "Simulation with Stack" },
      { title: "Remove K Digits",  leetcodeUrl: "https://leetcode.com/problems/remove-k-digits/", articleUrl: "", pattern: "Monotonic Stack" },
      { title: "Largest Rectangle in Histogram",  leetcodeUrl: "https://leetcode.com/problems/largest-rectangle-in-histogram/", articleUrl: "", pattern: "Monotonic Stack" },
      { title: "Maximal Rectangle",  leetcodeUrl: "https://leetcode.com/problems/maximal-rectangle/", articleUrl: "", pattern: "2D Histogram" },
      { title: "Sliding Window Maximum",  leetcodeUrl: "https://leetcode.com/problems/sliding-window-maximum/", articleUrl: "", pattern: "Monotonic Deque" },
      { title: "Stock Span Problem",  url: "https://www.geeksforgeeks.org/problems/stock-span-problem-1587115621/1", articleUrl: "", pattern: "Monotonic Stack" },
      { title: "Celebrity Problem",  url: "https://www.geeksforgeeks.org/problems/the-celebrity-problem/1", articleUrl: "", pattern: "Indegree/Outdegree" },
      { title: "LRU Cache Implementation",  leetcodeUrl: "https://leetcode.com/problems/lru-cache/", articleUrl: "", pattern: "Design" },
      { title: "LFU Cache Implementation",  leetcodeUrl: "https://leetcode.com/problems/lfu-cache/", articleUrl: "", pattern: "Design" },
    ]
  },
  {
    name: 'Greedy',
    icon: '📊',
    color: '#10b981',
    problems: [
      { title: "Gas Station",  leetcodeUrl: "https://leetcode.com/problems/gas-station/", articleUrl: "", pattern: "Greedy Circular" },
      { title: "Jump Game I",  leetcodeUrl: "https://leetcode.com/problems/jump-game/", articleUrl: "", pattern: "Greedy Reachability" },
      { title: "Jump Game II",  leetcodeUrl: "https://leetcode.com/problems/jump-game-ii/", articleUrl: "", pattern: "Greedy BFS-like" },
      { title: "Min Platforms",  url: "https://www.geeksforgeeks.org/problems/minimum-platforms-1587115620/1", articleUrl: "", pattern: "Sweep Line / Greedy" },
      { title: "N Meetings in One Room",  url: "https://www.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1", articleUrl: "", pattern: "Activity Selection" },
      { title: "Job Sequencing Problem",  url: "https://www.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1", articleUrl: "", pattern: "Greedy with Deadline" },
      { title: "Fractional Knapsack",  url: "https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1", articleUrl: "", pattern: "Greedy by Ratio" },
      { title: "Assign Cookies",  leetcodeUrl: "https://leetcode.com/problems/assign-cookies/", articleUrl: "", pattern: "Two Pointer / Greedy" },
      { title: "Lemonade Change",  leetcodeUrl: "https://leetcode.com/problems/lemonade-change/", articleUrl: "", pattern: "Greedy Simulation" },
      { title: "Shortest Job First (SJF)",  url: "https://www.geeksforgeeks.org/problems/shortest-job-first/1", articleUrl: "", pattern: "CPU Scheduling" },
      { title: "Insert Interval",  leetcodeUrl: "https://leetcode.com/problems/insert-interval/", articleUrl: "", pattern: "Interval Greedy" },
      { title: "Merge Intervals",  leetcodeUrl: "https://leetcode.com/problems/merge-intervals/", articleUrl: "", pattern: "Interval Sorting" },
      { title: "Non-overlapping Intervals",  leetcodeUrl: "https://leetcode.com/problems/non-overlapping-intervals/", articleUrl: "", pattern: "Interval Greedy" },
      { title: "Candy",  leetcodeUrl: "https://leetcode.com/problems/candy/", articleUrl: "", pattern: "Two-pass Greedy" },
    ]
  },
  {
    name: 'Heaps',
    icon: '🔍',
    color: '#06b6d4',
    problems: [
      { title: "Kth Largest Element in an Array",  leetcodeUrl: "https://leetcode.com/problems/kth-largest-element-in-an-array/", articleUrl: "", pattern: "Heap / QuickSelect" },
      { title: "Kth Smallest Element in a Sorted Matrix",  leetcodeUrl: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/", articleUrl: "", pattern: "Heap" },
      { title: "Top K Frequent Elements",  leetcodeUrl: "https://leetcode.com/problems/top-k-frequent-elements/", articleUrl: "", pattern: "Heap + HashMap" },
      { title: "Find Median from Data Stream",  leetcodeUrl: "https://leetcode.com/problems/find-median-from-data-stream/", articleUrl: "", pattern: "Two Heaps" },
      { title: "Merge K Sorted Arrays",  leetcodeUrl: "https://leetcode.com/problems/merge-k-sorted-lists/", articleUrl: "", pattern: "Heap / Divide & Conquer" },
      { title: "Replace Elements by Rank",  leetcodeUrl: "", articleUrl: "", pattern: "Sorting / Hashing" },
      { title: "Task Scheduler",  leetcodeUrl: "https://leetcode.com/problems/task-scheduler/", articleUrl: "", pattern: "Greedy + Heap" },
      { title: "Hand of Straights",  leetcodeUrl: "https://leetcode.com/problems/hand-of-straights/", articleUrl: "", pattern: "TreeMap / Heap" },
      { title: "Design Twitter",  leetcodeUrl: "https://leetcode.com/problems/design-twitter/", articleUrl: "", pattern: "Design + Heap" },
      { title: "Connect N Ropes with Minimum Cost",  url: "https://www.geeksforgeeks.org/problems/minimum-cost-of-ropes-1587115620/1", articleUrl: "", pattern: "Greedy Heap" },
      { title: "K Most Frequent Elements in Data Stream",  url: "https://www.geeksforgeeks.org/problems/top-k-frequent-elements-in-array/1", articleUrl: "", pattern: "Heap + HashMap" },
      { title: "Maximum Sum Combinations",  leetcodeUrl: "https://www.interviewbit.com/problems/maximum-sum-combinations/", articleUrl: "", pattern: "Heap" },
      { title: "Convert Min Heap to Max Heap",  leetcodeUrl: "", articleUrl: "", pattern: "Heapify" },
      { title: "Sort a K Sorted Array",  url: "https://www.geeksforgeeks.org/problems/nearly-sorted-1587115620/1", articleUrl: "", pattern: "Nearly Sorted Heap" },
    ]
  },
  {
    name: 'Binary Trees',
    icon: '📝',
    color: '#f59e0b',
    problems: [
      { title: "All Root to Leaf Paths in Binary Tree",  url: "https://www.geeksforgeeks.org/problems/root-to-leaf-paths/1", articleUrl: "", pattern: "Tree Traversal" },
      { title: "Height of Binary Tree",  leetcodeUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", articleUrl: "", pattern: "Tree DFS" },
      { title: "Balanced Binary Tree",  leetcodeUrl: "https://leetcode.com/problems/balanced-binary-tree/", articleUrl: "", pattern: "Tree DFS" },
      { title: "Diameter of Binary Tree",  leetcodeUrl: "https://leetcode.com/problems/diameter-of-binary-tree/", articleUrl: "", pattern: "Tree DFS" },
      { title: "Maximum Path Sum",  leetcodeUrl: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", articleUrl: "", pattern: "Tree DFS" },
      { title: "Identical Trees",  url: "https://www.geeksforgeeks.org/problems/determine-if-two-trees-are-identical/1", articleUrl: "", pattern: "Tree DFS/BFS" },
      { title: "Symmetric Tree",  leetcodeUrl: "https://leetcode.com/problems/symmetric-tree/", articleUrl: "", pattern: "Tree Traversal" },
      { title: "Zig-Zag Traversal",  leetcodeUrl: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", articleUrl: "", pattern: "BFS with Deque" },
      { title: "Boundary Traversal",  url: "https://www.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1", articleUrl: "", pattern: "Tree Traversal" },
      { title: "Vertical Order Traversal",  leetcodeUrl: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", articleUrl: "", pattern: "Tree BFS + Map" },
      { title: "Top View of Binary Tree",  url: "https://www.geeksforgeeks.org/problems/top-view-of-binary-tree/1", articleUrl: "", pattern: "Tree BFS + Map" },
      { title: "Bottom View of Binary Tree",  url: "https://www.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1", articleUrl: "", pattern: "Tree BFS + Map" },
      { title: "Left View of Binary Tree",  url: "https://www.geeksforgeeks.org/problems/left-view-of-binary-tree/1", articleUrl: "", pattern: "Tree BFS/DFS" },
      { title: "Right View of Binary Tree",  leetcodeUrl: "https://leetcode.com/problems/binary-tree-right-side-view/", articleUrl: "", pattern: "Tree BFS/DFS" },
      { title: "Preorder Traversal (Iterative)",  leetcodeUrl: "https://leetcode.com/problems/binary-tree-preorder-traversal/", articleUrl: "", pattern: "Tree Stack" },
      { title: "Inorder Traversal (Iterative)",  leetcodeUrl: "https://leetcode.com/problems/binary-tree-inorder-traversal/", articleUrl: "", pattern: "Tree Stack" },
      { title: "Postorder Traversal (Iterative)",  leetcodeUrl: "https://leetcode.com/problems/binary-tree-postorder-traversal/", articleUrl: "", pattern: "Tree Stack" },
      { title: "Morris Inorder Traversal",  leetcodeUrl: "", articleUrl: "", pattern: "Threaded Tree" },
      { title: "Morris Preorder Traversal",  leetcodeUrl: "", articleUrl: "", pattern: "Threaded Tree" },
      { title: "Flatten Binary Tree to Linked List",  leetcodeUrl: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", articleUrl: "", pattern: "Tree Manipulation" },
      { title: "Construct Binary Tree from Inorder and Preorder",  leetcodeUrl: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", articleUrl: "", pattern: "Recursive Build" },
      { title: "Construct Binary Tree from Inorder and Postorder",  leetcodeUrl: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/", articleUrl: "", pattern: "Recursive Build" },
      { title: "Serialize and Deserialize Binary Tree",  leetcodeUrl: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", articleUrl: "", pattern: "Design + Traversal" },
      { title: "Lowest Common Ancestor",  leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", articleUrl: "", pattern: "Tree DFS" },
      { title: "Print Root to Node Path",  url: "https://www.geeksforgeeks.org/problems/root-to-leaf-paths/1", articleUrl: "", pattern: "Tree DFS" },
      { title: "Maximum Width of Binary Tree",  leetcodeUrl: "https://leetcode.com/problems/maximum-width-of-binary-tree/", articleUrl: "", pattern: "BFS with Indexing" },
      { title: "Children Sum Property",  url: "https://www.geeksforgeeks.org/problems/children-sum-parent/1", articleUrl: "", pattern: "Tree Modification" },
      { title: "Nodes at Distance K",  leetcodeUrl: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", articleUrl: "", pattern: "BFS + Parent Map" },
      { title: "Count Total Nodes in Complete Binary Tree",  leetcodeUrl: "https://leetcode.com/problems/count-complete-tree-nodes/", articleUrl: "", pattern: "Complete Tree Property" },
      { title: "Requirements to Construct a Unique Binary Tree",  leetcodeUrl: "", articleUrl: "", pattern: "Theory" },
    ]
  },
  {
    name: 'Binary Search Trees',
    icon: '🔗',
    color: '#8b5cf6',
    problems: [
      { title: "BST Search",  url: "https://www.geeksforgeeks.org/problems/search-a-node-in-bst/1", articleUrl: "", pattern: "BST Property" },
      { title: "Insert into BST",  leetcodeUrl: "https://leetcode.com/problems/insert-into-a-binary-search-tree/", articleUrl: "", pattern: "BST Insertion" },
      { title: "Delete Node in BST",  leetcodeUrl: "https://leetcode.com/problems/delete-node-in-a-bst/", articleUrl: "", pattern: "BST Deletion" },
      { title: "Ceil in BST",  url: "https://www.geeksforgeeks.org/problems/implementing-ceil-in-bst/1", articleUrl: "", pattern: "BST Traversal" },
      { title: "Floor in BST",  url: "https://www.geeksforgeeks.org/problems/floor-in-bst/1", articleUrl: "", pattern: "BST Traversal" },
      { title: "Check for BST",  leetcodeUrl: "https://leetcode.com/problems/validate-binary-search-tree/", articleUrl: "", pattern: "Valid BST" },
      { title: "K-th Smallest in BST",  leetcodeUrl: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", articleUrl: "", pattern: "BST Inorder" },
      { title: "K-th Largest in BST",  url: "https://www.geeksforgeeks.org/problems/kth-largest-element-in-bst/1", articleUrl: "", pattern: "BST Reverse Inorder" },
      { title: "LCA in BST",  leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", articleUrl: "", pattern: "BST Property" },
      { title: "Construct BST from Preorder",  leetcodeUrl: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/", articleUrl: "", pattern: "Build BST" },
      { title: "Inorder Successor/Predecessor in BST",  url: "https://www.geeksforgeeks.org/problems/predecessor-and-successor/1", articleUrl: "", pattern: "BST Traversal" },
      { title: "Merge Two BSTs",  url: "https://www.geeksforgeeks.org/problems/merge-two-bst-s/1", articleUrl: "", pattern: "BST to DLL + Merge" },
      { title: "Two Sum in BST",  leetcodeUrl: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/", articleUrl: "", pattern: "BST Iterator" },
      { title: "Recover BST",  leetcodeUrl: "https://leetcode.com/problems/recover-binary-search-tree/", articleUrl: "", pattern: "BST Correction" },
      { title: "Largest BST in Binary Tree",  url: "https://www.geeksforgeeks.org/problems/largest-bst/1", articleUrl: "", pattern: "Postorder Check" },
    ]
  },
  {
    name: 'Graphs',
    icon: '🌳',
    color: '#f43f5e',
    problems: [
      { title: "Clone Graph",  leetcodeUrl: "https://leetcode.com/problems/clone-graph/", articleUrl: "", pattern: "DFS/BFS" },
      { title: "DFS of Graph",  url: "https://www.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1", articleUrl: "", pattern: "Graph Traversal" },
      { title: "BFS of Graph",  url: "https://www.geeksforgeeks.org/problems/bfs-traversal-of-graph/1", articleUrl: "", pattern: "Graph Traversal" },
      { title: "Detect Cycle in Undirected Graph (BFS)",  url: "https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1", articleUrl: "", pattern: "Cycle Detection BFS" },
      { title: "Detect Cycle in Undirected Graph (DFS)",  url: "https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1", articleUrl: "", pattern: "Cycle Detection DFS" },
      { title: "Detect Cycle in Directed Graph (DFS)",  url: "https://www.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1", articleUrl: "", pattern: "DFS with Recursion Stack" },
      { title: "Detect Cycle in Directed Graph (BFS/Kahn's)",  leetcodeUrl: "", articleUrl: "", pattern: "Topological Sort" },
      { title: "Topological Sort (DFS)",  url: "https://www.geeksforgeeks.org/problems/topological-sort/1", articleUrl: "", pattern: "Topological Sort" },
      { title: "Topological Sort (BFS - Kahn's)",  url: "https://www.geeksforgeeks.org/problems/topological-sort/1", articleUrl: "", pattern: "Topological Sort" },
      { title: "Number of Provinces",  leetcodeUrl: "https://leetcode.com/problems/number-of-provinces/", articleUrl: "", pattern: "Connected Components" },
      { title: "Number of Islands",  leetcodeUrl: "https://leetcode.com/problems/number-of-islands/", articleUrl: "", pattern: "BFS/DFS on Grid" },
      { title: "Flood Fill",  leetcodeUrl: "https://leetcode.com/problems/flood-fill/", articleUrl: "", pattern: "BFS/DFS on Grid" },
      { title: "Rotten Oranges",  leetcodeUrl: "https://leetcode.com/problems/rotting-oranges/", articleUrl: "", pattern: "BFS on Grid" },
      { title: "Course Schedule I",  leetcodeUrl: "https://leetcode.com/problems/course-schedule/", articleUrl: "", pattern: "Cycle Detection (Topo)" },
      { title: "Course Schedule II",  leetcodeUrl: "https://leetcode.com/problems/course-schedule-ii/", articleUrl: "", pattern: "Topological Sort" },
      { title: "Alien Dictionary",  url: "https://www.geeksforgeeks.org/problems/alien-dictionary/1", articleUrl: "", pattern: "Topological Sort" },
      { title: "Shortest Path in DAG",  leetcodeUrl: "", articleUrl: "", pattern: "Shortest Path" },
      { title: "Shortest Path in Undirected Graph (Unit Weights)",  url: "https://www.geeksforgeeks.org/problems/shortest-path-in-undirected-graph-having-unit-distance/1", articleUrl: "", pattern: "BFS Shortest Path" },
      { title: "Word Ladder I",  leetcodeUrl: "https://leetcode.com/problems/word-ladder/", articleUrl: "", pattern: "BFS on Words" },
      { title: "Word Ladder II",  leetcodeUrl: "https://leetcode.com/problems/word-ladder-ii/", articleUrl: "", pattern: "BFS + DFS Backtrack" },
      { title: "Dijkstra's Algorithm (Priority Queue)",  url: "https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1", articleUrl: "", pattern: "Shortest Path" },
      { title: "Dijkstra's Algorithm (Set)",  leetcodeUrl: "", articleUrl: "", pattern: "Shortest Path" },
      { title: "Bellman Ford Algorithm",  url: "https://www.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1", articleUrl: "", pattern: "Shortest Path (Neg)" },
      { title: "Floyd Warshall Algorithm",  url: "https://www.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1", articleUrl: "", pattern: "All Pairs Shortest Path" },
      { title: "Prim's Algorithm (MST)",  url: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1", articleUrl: "", pattern: "MST" },
      { title: "Kruskal's Algorithm (MST)",  url: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1", articleUrl: "", pattern: "MST" },
      { title: "Cheapest Flights Within K Stops",  leetcodeUrl: "https://leetcode.com/problems/cheapest-flights-within-k-stops/", articleUrl: "", pattern: "Modified Dijkstra" },
      { title: "Network Delay Time",  leetcodeUrl: "https://leetcode.com/problems/network-delay-time/", articleUrl: "", pattern: "Dijkstra" },
      { title: "Path with Minimum Effort",  leetcodeUrl: "https://leetcode.com/problems/path-with-minimum-effort/", articleUrl: "", pattern: "Dijkstra Variation" },
      { title: "Shortest Path in Binary Matrix",  leetcodeUrl: "https://leetcode.com/problems/shortest-path-in-binary-matrix/", articleUrl: "", pattern: "BFS on Grid" },
      { title: "Number of Ways to Arrive at Destination",  leetcodeUrl: "https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/", articleUrl: "", pattern: "Dijkstra with Count" },
      { title: "Minimum Multiplications to Reach End",  url: "https://www.geeksforgeeks.org/problems/minimum-multiplications-to-reach-end/1", articleUrl: "", pattern: "BFS / Dijkstra" },
      { title: "Articulation Point",  url: "https://www.geeksforgeeks.org/problems/articulation-point-1/1", articleUrl: "", pattern: "Tarjan's / DFS" },
      { title: "Bridges in Graph",  leetcodeUrl: "https://leetcode.com/problems/critical-connections-in-a-network/", articleUrl: "", pattern: "Tarjan's" },
      { title: "Kosaraju's Algorithm",  url: "https://www.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1", articleUrl: "", pattern: "SCC" },
      { title: "Tarjan's Algorithm for SCC",  leetcodeUrl: "", articleUrl: "", pattern: "SCC" },
    ]
  },
  {
    name: 'Dynamic Programming',
    icon: '🌲',
    color: '#3b82f6',
    problems: [
      { title: "1D DP Introduction",  leetcodeUrl: "", articleUrl: "", pattern: "DP Fundamentals" },
      { title: "Climbing Stairs",  leetcodeUrl: "https://leetcode.com/problems/climbing-stairs/", articleUrl: "", pattern: "Fibonacci DP" },
      { title: "Frog Jump (Energy Problem)",  leetcodeUrl: "", articleUrl: "", pattern: "DP on Array" },
      { title: "Frog Jump with K Distance",  leetcodeUrl: "", articleUrl: "", pattern: "DP on Array" },
      { title: "House Robber",  leetcodeUrl: "https://leetcode.com/problems/house-robber/", articleUrl: "", pattern: "Max Non-Adjacent Sum" },
      { title: "House Robber II",  leetcodeUrl: "https://leetcode.com/problems/house-robber-ii/", articleUrl: "", pattern: "Circular DP" },
      { title: "Ninja's Training",  leetcodeUrl: "", articleUrl: "", pattern: "2D DP" },
      { title: "Unique Paths",  leetcodeUrl: "https://leetcode.com/problems/unique-paths/", articleUrl: "", pattern: "Grid DP" },
      { title: "Unique Paths II",  leetcodeUrl: "https://leetcode.com/problems/unique-paths-ii/", articleUrl: "", pattern: "Grid DP with Obstacles" },
      { title: "Minimum Path Sum",  leetcodeUrl: "https://leetcode.com/problems/minimum-path-sum/", articleUrl: "", pattern: "Grid DP" },
      { title: "Triangle Minimum Path Sum",  leetcodeUrl: "https://leetcode.com/problems/triangle/", articleUrl: "", pattern: "Grid DP" },
      { title: "Minimum Falling Path Sum",  leetcodeUrl: "https://leetcode.com/problems/minimum-falling-path-sum/", articleUrl: "", pattern: "Grid DP" },
      { title: "Cherry Pickup (3D DP)",  leetcodeUrl: "https://leetcode.com/problems/cherry-pickup/", articleUrl: "", pattern: "3D DP" },
      { title: "Subset Sum Equals to K",  leetcodeUrl: "", articleUrl: "", pattern: "Subset Sum DP" },
      { title: "Partition Equal Subset Sum",  leetcodeUrl: "https://leetcode.com/problems/partition-equal-subset-sum/", articleUrl: "", pattern: "Subset Sum DP" },
      { title: "Count Subsets with Sum K",  url: "https://www.geeksforgeeks.org/problems/perfect-sum-problem5633/1", articleUrl: "", pattern: "Subset Sum DP" },
      { title: "Partition Set Into 2 Subsets with Min Absolute Diff",  url: "https://www.geeksforgeeks.org/problems/minimum-sum-partition3317/1", articleUrl: "", pattern: "Subset Sum DP" },
      { title: "Count Partitions with Given Difference",  url: "https://www.geeksforgeeks.org/problems/partitions-with-given-difference/1", articleUrl: "", pattern: "Subset Sum DP" },
      { title: "0/1 Knapsack",  url: "https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1", articleUrl: "", pattern: "Knapsack DP" },
      { title: "Coin Change (Minimum Coins)",  leetcodeUrl: "https://leetcode.com/problems/coin-change/", articleUrl: "", pattern: "Unbounded Knapsack" },
      { title: "Coin Change II (Ways)",  leetcodeUrl: "https://leetcode.com/problems/coin-change-ii/", articleUrl: "", pattern: "Unbounded Knapsack" },
      { title: "Rod Cutting",  url: "https://www.geeksforgeeks.org/problems/rod-cutting0840/1", articleUrl: "", pattern: "Unbounded Knapsack" },
      { title: "Longest Common Subsequence",  leetcodeUrl: "https://leetcode.com/problems/longest-common-subsequence/", articleUrl: "", pattern: "String DP" },
      { title: "Print LCS",  leetcodeUrl: "", articleUrl: "", pattern: "String DP" },
      { title: "Longest Common Substring",  url: "https://www.geeksforgeeks.org/problems/longest-common-substring1452/1", articleUrl: "", pattern: "String DP" },
      { title: "Longest Palindromic Subsequence",  leetcodeUrl: "https://leetcode.com/problems/longest-palindromic-subsequence/", articleUrl: "", pattern: "String DP" },
      { title: "Minimum Insertions to Make String Palindrome",  leetcodeUrl: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/", articleUrl: "", pattern: "String DP" },
      { title: "Delete Operation for Two Strings",  leetcodeUrl: "https://leetcode.com/problems/delete-operation-for-two-strings/", articleUrl: "", pattern: "String DP" },
      { title: "Shortest Common Supersequence",  leetcodeUrl: "https://leetcode.com/problems/shortest-common-supersequence/", articleUrl: "", pattern: "String DP" },
      { title: "Distinct Subsequences",  leetcodeUrl: "https://leetcode.com/problems/distinct-subsequences/", articleUrl: "", pattern: "String DP" },
      { title: "Edit Distance",  leetcodeUrl: "https://leetcode.com/problems/edit-distance/", articleUrl: "", pattern: "String DP" },
      { title: "Wildcard Matching",  leetcodeUrl: "https://leetcode.com/problems/wildcard-matching/", articleUrl: "", pattern: "String DP" },
      { title: "Best Time to Buy and Sell Stock II",  leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/", articleUrl: "", pattern: "Stock DP" },
      { title: "Best Time to Buy and Sell Stock III",  leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/", articleUrl: "", pattern: "Stock DP" },
      { title: "Best Time to Buy and Sell Stock IV",  leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", articleUrl: "", pattern: "Stock DP" },
      { title: "Best Time to Buy and Sell Stock with Cooldown",  leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/", articleUrl: "", pattern: "Stock DP" },
      { title: "Best Time to Buy and Sell Stock with Transaction Fee",  leetcodeUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/", articleUrl: "", pattern: "Stock DP" },
      { title: "Longest Increasing Subsequence (LIS)",  leetcodeUrl: "https://leetcode.com/problems/longest-increasing-subsequence/", articleUrl: "", pattern: "LIS DP" },
      { title: "Print LIS",  leetcodeUrl: "", articleUrl: "", pattern: "LIS DP" },
      { title: "LIS using Binary Search",  leetcodeUrl: "https://leetcode.com/problems/longest-increasing-subsequence/", articleUrl: "", pattern: "LIS DP + Binary Search" },
      { title: "Largest Divisible Subset",  leetcodeUrl: "https://leetcode.com/problems/largest-divisible-subset/", articleUrl: "", pattern: "LIS Variation" },
      { title: "Longest String Chain",  leetcodeUrl: "https://leetcode.com/problems/longest-string-chain/", articleUrl: "", pattern: "LIS Variation" },
      { title: "Longest Bitonic Subsequence",  url: "https://www.geeksforgeeks.org/problems/longest-bitonic-subsequence0824/1", articleUrl: "", pattern: "LIS Variation" },
      { title: "Number of Longest Increasing Subsequence",  leetcodeUrl: "https://leetcode.com/problems/number-of-longest-increasing-subsequence/", articleUrl: "", pattern: "LIS DP" },
      { title: "Matrix Chain Multiplication",  url: "https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1", articleUrl: "", pattern: "Partition DP" },
      { title: "Minimum Cost to Cut Stick",  leetcodeUrl: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", articleUrl: "", pattern: "Partition DP" },
      { title: "Burst Balloons",  leetcodeUrl: "https://leetcode.com/problems/burst-balloons/", articleUrl: "", pattern: "Partition DP" },
      { title: "Palindrome Partitioning II",  leetcodeUrl: "https://leetcode.com/problems/palindrome-partitioning-ii/", articleUrl: "", pattern: "Partition DP" },
      { title: "Partition Array for Maximum Sum",  leetcodeUrl: "https://leetcode.com/problems/partition-array-for-maximum-sum/", articleUrl: "", pattern: "Partition DP" },
      { title: "Maximum Rectangle Area with all 1's",  leetcodeUrl: "https://leetcode.com/problems/maximal-rectangle/", articleUrl: "", pattern: "Maximal Rectangle DP" },
      { title: "Count Square Submatrices with all 1s",  leetcodeUrl: "https://leetcode.com/problems/count-square-submatrices-with-all-ones/", articleUrl: "", pattern: "DP on Grid" },
      { title: "Minimum Cost Path (Grid)",  url: "https://www.geeksforgeeks.org/problems/minimum-cost-path3833/1", articleUrl: "", pattern: "Grid DP" },
      { title: "Minimum Falling Path Sum II",  leetcodeUrl: "https://leetcode.com/problems/minimum-falling-path-sum-ii/", articleUrl: "", pattern: "Grid DP" },
      { title: "Maximum Sum of Non-Adjacent Elements (Stickler Thief)",  url: "https://www.geeksforgeeks.org/problems/stickler-theif-1587115621/1", articleUrl: "", pattern: "DP on Array" },
    ]
  },
  {
    name: 'Trie',
    icon: '🕸️',
    color: '#ec4899',
    problems: [
      { title: "Implement Trie (Prefix Tree)",  leetcodeUrl: "https://leetcode.com/problems/implement-trie-prefix-tree/", articleUrl: "", pattern: "Trie Implementation" },
      { title: "Implement Trie - II (Count Words)",  leetcodeUrl: "", articleUrl: "", pattern: "Trie Design" },
      { title: "Longest Word in Dictionary",  leetcodeUrl: "https://leetcode.com/problems/longest-word-in-dictionary/", articleUrl: "", pattern: "Trie + Sorting" },
      { title: "Number of Distinct Substrings in a String",  url: "https://www.geeksforgeeks.org/problems/count-of-distinct-substrings/1", articleUrl: "", pattern: "Count Substrings" },
      { title: "Maximum XOR of Two Numbers in an Array",  leetcodeUrl: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", articleUrl: "", pattern: "Bit Trie" },
    ]
  },
  {
    name: 'Recursion / Backtracking',
    icon: '🧮',
    color: '#84cc16',
    problems: [
      { title: "Power Set (Subsets)",  leetcodeUrl: "https://leetcode.com/problems/subsets/", articleUrl: "", pattern: "Recursion / Iterative" },
      { title: "Subsets II",  leetcodeUrl: "https://leetcode.com/problems/subsets-ii/", articleUrl: "", pattern: "Recursion + Avoid Duplicates" },
      { title: "Combination Sum I",  leetcodeUrl: "https://leetcode.com/problems/combination-sum/", articleUrl: "", pattern: "Combination Sum" },
      { title: "Combination Sum II",  leetcodeUrl: "https://leetcode.com/problems/combination-sum-ii/", articleUrl: "", pattern: "Combination Sum + No Reuse" },
      { title: "Combination Sum III",  leetcodeUrl: "https://leetcode.com/problems/combination-sum-iii/", articleUrl: "", pattern: "Combination Sum k numbers" },
      { title: "Palindrome Partitioning",  leetcodeUrl: "https://leetcode.com/problems/palindrome-partitioning/", articleUrl: "", pattern: "Partitioning" },
      { title: "Permutations I",  leetcodeUrl: "https://leetcode.com/problems/permutations/", articleUrl: "", pattern: "All Arrangements" },
      { title: "Permutations II",  leetcodeUrl: "https://leetcode.com/problems/permutations-ii/", articleUrl: "", pattern: "Unique Permutations" },
      { title: "N-Queens",  leetcodeUrl: "https://leetcode.com/problems/n-queens/", articleUrl: "", pattern: "Constraint Satisfaction" },
      { title: "Word Break (Backtracking)",  leetcodeUrl: "https://leetcode.com/problems/word-break/", articleUrl: "", pattern: "Word Segmentation" },
      { title: "Sudoku Solver",  leetcodeUrl: "https://leetcode.com/problems/sudoku-solver/", articleUrl: "", pattern: "Constraint Satisfaction" },
      { title: "M-Coloring Problem",  url: "https://www.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1", articleUrl: "", pattern: "Graph Coloring" },
      { title: "Rat in a Maze",  url: "https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1", articleUrl: "", pattern: "Grid Pathfinding" },
      { title: "K-th Permutation Sequence",  leetcodeUrl: "https://leetcode.com/problems/permutation-sequence/", articleUrl: "", pattern: "Math + Recursion" },
    ]
  },
  {
    name: 'Bit Manipulation',
    icon: '🎲',
    color: '#14b8a6',
    problems: [
      { title: "Bit Manipulation Introduction",  leetcodeUrl: "", articleUrl: "", pattern: "Bit Basics" },
      { title: "Check if i-th Bit is Set",  leetcodeUrl: "", articleUrl: "", pattern: "Bit Mask" },
      { title: "Set i-th Bit",  leetcodeUrl: "", articleUrl: "", pattern: "Bit Mask" },
      { title: "Clear i-th Bit",  leetcodeUrl: "", articleUrl: "", pattern: "Bit Mask" },
      { title: "Toggle i-th Bit",  leetcodeUrl: "", articleUrl: "", pattern: "Bit Mask" },
      { title: "Remove Last Set Bit",  leetcodeUrl: "", articleUrl: "", pattern: "Bit Trick" },
      { title: "Count Set Bits",  leetcodeUrl: "https://leetcode.com/problems/number-of-1-bits/", articleUrl: "", pattern: "Bit Count" },
      { title: "Power of Two",  leetcodeUrl: "https://leetcode.com/problems/power-of-two/", articleUrl: "", pattern: "Bit Check" },
      { title: "Single Number",  leetcodeUrl: "https://leetcode.com/problems/single-number/", articleUrl: "", pattern: "XOR" },
      { title: "Single Number II",  leetcodeUrl: "https://leetcode.com/problems/single-number-ii/", articleUrl: "", pattern: "Bit Count/State" },
      { title: "Single Number III",  leetcodeUrl: "https://leetcode.com/problems/single-number-iii/", articleUrl: "", pattern: "XOR + Bucket" },
      { title: "Divide Two Integers",  leetcodeUrl: "https://leetcode.com/problems/divide-two-integers/", articleUrl: "", pattern: "Bit Shifts" },
      { title: "Minimum Bit Flips to Convert Number",  leetcodeUrl: "https://leetcode.com/problems/minimum-bit-flips-to-convert-number/", articleUrl: "", pattern: "XOR" },
      { title: "Power Set using Bit Manipulation",  leetcodeUrl: "https://leetcode.com/problems/subsets/", articleUrl: "", pattern: "Bit Masking" },
      { title: "XOR of 1 to N",  leetcodeUrl: "", articleUrl: "", pattern: "XOR Pattern" },
      { title: "Two Numbers with Odd Occurrences",  url: "https://www.geeksforgeeks.org/problems/two-numbers-with-odd-occurrences5846/1", articleUrl: "", pattern: "XOR Buckets" },
      { title: "XOR of a Given Range",  leetcodeUrl: "", articleUrl: "", pattern: "Prefix XOR" },
    ]
  },
  {
    name: 'Sorting',
    icon: '🔍',
    color: '#06b6d4',
    problems: [
      { title: "Merge Sort",  url: "https://www.geeksforgeeks.org/problems/merge-sort/1", articleUrl: "", pattern: "Divide and Conquer" },
      { title: "Quick Sort",  url: "https://www.geeksforgeeks.org/problems/quick-sort/1", articleUrl: "", pattern: "Divide and Conquer" },
      { title: "Recursive Insertion Sort",  url: "https://www.geeksforgeeks.org/problems/insertion-sort/1", articleUrl: "", pattern: "Recursion" },
      { title: "Recursive Bubble Sort",  url: "https://www.geeksforgeeks.org/problems/bubble-sort/1", articleUrl: "", pattern: "Recursion" },
    ]
  },
];
